# Generated by Django 4.0.5 on 2022-06-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=8, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_writer', models.BooleanField()),
                ('rank', models.CharField(choices=[('BW', 'Bookworm'), ('GBW', 'Gold Bookworm'), ('PBW', 'Platinum Bookworm')], max_length=3)),
                ('bio', models.TextField(help_text='MAX LENGTH OF 500', max_length=500)),
            ],
        ),
    ]
