# Generated by Django 4.0.5 on 2022-06-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='NO BIO', help_text='MAX LENGTH OF 500', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_writer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('BW', 'Bookworm'), ('GBW', 'Gold Bookworm'), ('PBW', 'Platinum Bookworm')], default='BW', max_length=3),
        ),
    ]
