# Generated by Django 4.0.5 on 2022-06-17 23:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_remove_book_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.book')),
            ],
        ),
    ]
